import React, { useState, useEffect } from 'react';
import { CalculatorResult } from '../../types';
import { 
    calculateCHA2DS2VASc, calculateHASBLED, calculateHEARTScore, calculateFramingham2008
} from '../../utils/calculations';
import { ResultCard, InputGroup, NumberInput, Toggle, Checkbox, formatEMR } from './Shared';

export const CHA2DS2VAScCalculator: React.FC = () => { const [age, setAge] = useState<number|''>(''); const [sex, setSex] = useState<'male'|'female'>('male'); const [chf, setChf] = useState(false); const [htn, setHtn] = useState(false); const [stroke, setStroke] = useState(false); const [vascular, setVascular] = useState(false); const [dm, setDm] = useState(false); const [result, setResult] = useState<CalculatorResult|null>(null); useEffect(() => { if (age) setResult(calculateCHA2DS2VASc(Number(age), sex, chf, htn, stroke, vascular, dm)); else setResult(null); }, [age, sex, chf, htn, stroke, vascular, dm]); const copyText = formatEMR('CHA2DS2-VASc', `Age ${age}, ${sex}`, result); return ( <div className="max-w-md space-y-4"> <InputGroup label="性別"><Toggle options={[{value:'male', label:'男'}, {value:'female', label:'女 (+1)'}]} value={sex} onChange={setSex} /></InputGroup> <InputGroup label="年齡"><NumberInput value={age} onChange={setAge} placeholder="Age" /></InputGroup> <div className="space-y-3 pt-2"><Checkbox label="C: 心衰竭/LVEF異常 (+1)" checked={chf} onChange={setChf} /><Checkbox label="H: 高血壓 (+1)" checked={htn} onChange={setHtn} /><Checkbox label="D: 糖尿病 (+1)" checked={dm} onChange={setDm} /><Checkbox label="S: 中風/TIA/血栓史 (+2)" checked={stroke} onChange={setStroke} /><Checkbox label="V: 血管疾病 (MI/PAD) (+1)" checked={vascular} onChange={setVascular} /></div> <ResultCard title="CHA2DS2-VASc" result={result} copyContent={copyText} /> </div> ) };

export const HASBLEDCalculator: React.FC = () => { const [htn, setHtn] = useState(false); const [abRenal, setAbRenal] = useState(false); const [abLiver, setAbLiver] = useState(false); const [stroke, setStroke] = useState(false); const [bleed, setBleed] = useState(false); const [inr, setInr] = useState(false); const [elderly, setElderly] = useState(false); const [drugs, setDrugs] = useState(false); const [alc, setAlc] = useState(false); const [result, setResult] = useState<CalculatorResult|null>(null); useEffect(() => setResult(calculateHASBLED(htn, abRenal, abLiver, stroke, bleed, inr, elderly, drugs, alc)), [htn, abRenal, abLiver, stroke, bleed, inr, elderly, drugs, alc]); const copyText = formatEMR('HAS-BLED', '', result); return ( <div className="max-w-md space-y-3"> <Checkbox label="H: 高血壓" checked={htn} onChange={setHtn} /><Checkbox label="A: 腎功能異常" checked={abRenal} onChange={setAbRenal} /><Checkbox label="A: 肝功能異常" checked={abLiver} onChange={setAbLiver} /><Checkbox label="S: 中風病史" checked={stroke} onChange={setStroke} /><Checkbox label="B: 出血病史" checked={bleed} onChange={setBleed} /><Checkbox label="L: INR 不穩定" checked={inr} onChange={setInr} /><Checkbox label="E: 高齡 (>65)" checked={elderly} onChange={setElderly} /><Checkbox label="D: 藥物" checked={drugs} onChange={setDrugs} /><Checkbox label="D: 酒精" checked={alc} onChange={setAlc} /> <ResultCard title="HAS-BLED" result={result} copyContent={copyText} /> </div> ) }

export const HEARTScoreCalculator: React.FC = () => { const [h, setH] = useState(0); const [e, setE] = useState(0); const [a, setA] = useState(0); const [r, setR] = useState(0); const [t, setT] = useState(0); const [result, setResult] = useState<CalculatorResult | null>(null); useEffect(() => setResult(calculateHEARTScore(h, e, a, r, t)), [h, e, a, r, t]); const copyText = formatEMR('HEART Score', `H:${h}, E:${e}, A:${a}, R:${r}, T:${t}`, result); const Select: React.FC<{label: string, options: {val:number, txt:string}[], val: number, set: any}> = ({label, options, val, set}) => (<div className="mb-5"><label className="block text-base font-bold text-black mb-2">{label}</label><select value={val} onChange={e => set(Number(e.target.value))} className="w-full rounded-lg border-2 border-slate-300 py-3 px-2 text-base bg-white font-bold text-black focus:border-primary">{options.map(o => <option key={o.val} value={o.val}>{o.txt}</option>)}</select></div>); return ( <div className="max-w-md"> <Select label="History" val={h} set={setH} options={[{val: 0, txt: '不典型'},{val: 1, txt: '中度懷疑'},{val: 2, txt: '高度懷疑'}]} /> <Select label="ECG" val={e} set={setE} options={[{val: 0, txt: '正常'},{val: 1, txt: '非特異性變化'},{val: 2, txt: '顯著 ST 變化'}]} /> <Select label="Age" val={a} set={setA} options={[{val: 0, txt: '< 45'},{val: 1, txt: '45 - 65'},{val: 2, txt: '> 65'}]} /> <Select label="Risk Factors" val={r} set={setR} options={[{val: 0, txt: '無'},{val: 1, txt: '1-2 個'},{val: 2, txt: '≥3 個'}]} /> <Select label="Troponin" val={t} set={setT} options={[{val: 0, txt: '正常'},{val: 1, txt: '1-3x'},{val: 2, txt: '>3x'}]} /> <ResultCard title="HEART Score" result={result} copyContent={copyText} /> </div> ) }

export const FraminghamCalculator: React.FC = () => { const [age, setAge] = useState<number|''>(''); const [sex, setSex] = useState<'male'|'female'>('male'); const [smoker, setSmoker] = useState(false); const [diabetes, setDiabetes] = useState(false); const [treatedBP, setTreatedBP] = useState(false); const [sbp, setSbp] = useState<number|''>(''); const [tc, setTc] = useState<number|''>(''); const [hdl, setHdl] = useState<number|''>(''); const [result, setResult] = useState<CalculatorResult|null>(null); useEffect(() => { if(age && sbp && tc && hdl) setResult(calculateFramingham2008(Number(age), sex, smoker, diabetes, treatedBP, Number(sbp), Number(tc), Number(hdl))); else setResult(null); }, [age, sex, smoker, diabetes, treatedBP, sbp, tc, hdl]); const copyText = formatEMR('Framingham CVD', `${sex}, Age ${age}, Smk ${smoker}, DM ${diabetes}, SBP ${sbp}, TC ${tc}, HDL ${hdl}`, result); return ( <div className="max-w-md space-y-4"> <div className="grid grid-cols-2 gap-4"><InputGroup label="性別"><Toggle options={[{value:'male', label:'男'}, {value:'female', label:'女'}]} value={sex} onChange={setSex} /></InputGroup><InputGroup label="年齡"><NumberInput value={age} onChange={setAge} /></InputGroup></div> <div className="grid grid-cols-2 gap-4"><InputGroup label="TC"><NumberInput value={tc} onChange={setTc} placeholder="mg/dL" /></InputGroup><InputGroup label="HDL"><NumberInput value={hdl} onChange={setHdl} placeholder="mg/dL" /></InputGroup></div> <div className="grid grid-cols-2 gap-4"><InputGroup label="SBP"><NumberInput value={sbp} onChange={setSbp} placeholder="mmHg" /></InputGroup><div className="pt-8"><Checkbox label="服用血壓藥?" checked={treatedBP} onChange={setTreatedBP} /></div></div> <div className="grid grid-cols-2 gap-4"><Checkbox label="吸菸" checked={smoker} onChange={setSmoker} /><Checkbox label="糖尿病" checked={diabetes} onChange={setDiabetes} /></div> <ResultCard title="10-Year CVD Risk" result={result} copyContent={copyText} /> </div> ); };
