import React, { useState, useEffect } from 'react';
import { CalculatorResult } from '../../types';
import { calculateFib4, calculateAPRI, calculateChildPugh } from '../../utils/calculations';
import { ResultCard, InputGroup, NumberInput, Toggle, formatEMR } from './Shared';

export const Fib4Calculator: React.FC = () => { const [age, setAge] = useState<number | ''>(''); const [ast, setAst] = useState<number | ''>(''); const [alt, setAlt] = useState<number | ''>(''); const [plt, setPlt] = useState<number | ''>(''); const [result, setResult] = useState<CalculatorResult | null>(null); useEffect(() => { if (age && ast && alt && plt) setResult(calculateFib4(Number(age), Number(ast), Number(alt), Number(plt))); else setResult(null); }, [age, ast, alt, plt]); const copyText = formatEMR('Fib-4 Score', `Age ${age}, AST ${ast}, ALT ${alt}, PLT ${plt}`, result); return ( <div className="max-w-md grid grid-cols-2 gap-6"> <InputGroup label="年齡 (Age)"><NumberInput value={age} onChange={setAge} /></InputGroup> <InputGroup label="血小板 (10^3)"><NumberInput value={plt} onChange={setPlt} /></InputGroup> <InputGroup label="AST (U/L)"><NumberInput value={ast} onChange={setAst} /></InputGroup> <InputGroup label="ALT (U/L)"><NumberInput value={alt} onChange={setAlt} /></InputGroup> <div className="col-span-2"><ResultCard title="Fib-4" result={result} copyContent={copyText} /></div> </div> ); };

export const APRICalculator: React.FC = () => { const [ast, setAst] = useState<number | ''>(''); const [plt, setPlt] = useState<number | ''>(''); const [result, setResult] = useState<CalculatorResult | null>(null); useEffect(() => { if(ast && plt) setResult(calculateAPRI(Number(ast), Number(plt))); else setResult(null); }, [ast, plt]); const copyText = formatEMR('APRI Score', `AST ${ast}, PLT ${plt}`, result); return ( <div className="max-w-md"> <InputGroup label="AST (U/L)"><NumberInput value={ast} onChange={setAst} /></InputGroup> <InputGroup label="Platelet (10^3)"><NumberInput value={plt} onChange={setPlt} /></InputGroup> <ResultCard title="APRI" result={result} copyContent={copyText} /> </div> ) }

export const ChildPughCalculator: React.FC = () => { const [bili, setBili] = useState<number | ''>(''); const [alb, setAlb] = useState<number | ''>(''); const [inr, setInr] = useState<number | ''>(''); const [ascites, setAscites] = useState(1); const [enceph, setEnceph] = useState(1); const [result, setResult] = useState<CalculatorResult | null>(null); useEffect(() => { if(bili && alb && inr) setResult(calculateChildPugh(Number(bili), Number(alb), Number(inr), ascites, enceph)); else setResult(null); }, [bili, alb, inr, ascites, enceph]); const copyText = formatEMR('Child-Pugh', `Bili ${bili}, Alb ${alb}, INR ${inr}, As:${ascites}, En:${enceph}`, result); return ( <div className="max-w-md space-y-6"> <div className="grid grid-cols-2 gap-6"><InputGroup label="Bilirubin"><NumberInput value={bili} onChange={setBili} step="0.1" /></InputGroup><InputGroup label="Albumin"><NumberInput value={alb} onChange={setAlb} step="0.1" /></InputGroup></div> <InputGroup label="INR"><NumberInput value={inr} onChange={setInr} step="0.1" /></InputGroup> <InputGroup label="腹水"><Toggle options={[{value: 1, label: '無'}, {value: 2, label: '輕微'}, {value: 3, label: '中重度'}]} value={ascites} onChange={setAscites} /></InputGroup> <InputGroup label="肝腦病變"><Toggle options={[{value: 1, label: '無'}, {value: 2, label: 'G1-2'}, {value: 3, label: 'G3-4'}]} value={enceph} onChange={setEnceph} /></InputGroup> <ResultCard title="Child-Pugh" result={result} copyContent={copyText} /> </div> ); }
