import React, { useState, useEffect } from 'react';
import { CalculatorResult } from '../../types';
import { 
    calculateACT_Adult, calculateACT_Child, calculateCURB65, calculateABG, calculateMMRC, calculateCAT
} from '../../utils/calculations';
import { ResultCard, InputGroup, NumberInput, Toggle, Checkbox, formatEMR } from './Shared';
import { Info } from 'lucide-react';

export const ACTCalculator: React.FC = () => { const [mode, setMode] = useState<'adult'|'child'>('adult'); const [scores, setScores] = useState<number[]>([]); const [result, setResult] = useState<CalculatorResult|null>(null); useEffect(() => { setScores(mode === 'adult' ? new Array(5).fill(1) : new Array(7).fill(0)); }, [mode]); useEffect(() => { if (scores.length === 0) return; if (mode === 'adult') setResult(calculateACT_Adult(scores)); else setResult(calculateACT_Child(scores)); }, [scores, mode]); const copyText = formatEMR(mode === 'adult' ? 'ACT' : 'Child ACT', `Scores: [${scores.join(', ')}]`, result); const adultQuestions = ["1. 過去4週，氣喘讓你無法完成工作的頻率？", "2. 過去4週，感覺呼吸困難的頻率？", "3. 過去4週，因氣喘夜間醒來或早起的頻率？", "4. 過去4週，使用急救藥物(緩解劑)的頻率？", "5. 過去4週，您覺得氣喘控制得如何？"]; const adultOpts = [["全部時間(1)", "大部分時間(2)", "有些時間(3)", "很少時間(4)", "完全沒有(5)"], ["每天大於一次(1)", "每天一次(2)", "每週3-6次(3)", "每週1-2次(4)", "完全沒有(5)"], ["每週4晚以上(1)", "每週2-3晚(2)", "每週1次(3)", "1-2次(4)", "完全沒有(5)"], ["每天3次以上(1)", "每天1-2次(2)", "每週2-3次(3)", "每週1次或更少(4)", "完全沒有(5)"], ["完全沒控制(1)", "控制不佳(2)", "有些控制(3)", "控制良好(4)", "完全控制(5)"]]; const childQuestions = ["1. 運動或跑步時氣喘情形? (0-3)", "2. 咳嗽情形? (0-3)", "3. 夜間醒來? (0-3)", "4. 覺得氣喘情形? (0-3)", "5. 孩子白天氣喘症狀天數? (0-5)", "6. 孩子白天喘鳴天數? (0-5)", "7. 孩子夜間醒來天數? (0-5)"]; const updateScore = (idx: number, val: number) => { const ns = [...scores]; ns[idx] = val; setScores(ns); }; return ( <div className="max-w-2xl"> <div className="mb-6"> <Toggle options={[{value: 'adult', label: '成人 ACT (>12歲)'}, {value: 'child', label: '兒童 c-ACT (4-11歲)'}]} value={mode} onChange={setMode} /> </div> {mode === 'adult' ? ( <div className="space-y-5"> {adultQuestions.map((q, idx) => ( <div key={idx} className="bg-white p-5 rounded-lg border-2 border-slate-200 shadow-sm"> <p className="font-bold text-black text-base mb-3">{q}</p> <select className="w-full text-base rounded-md border-2 border-slate-300 py-2.5 bg-white text-black font-bold" value={scores[idx]} onChange={e => updateScore(idx, Number(e.target.value))}> {adultOpts[idx].map((opt, i) => <option key={i} value={i+1}>{opt}</option>)} </select> </div> ))} </div> ) : ( <div className="space-y-5"> <div className="bg-amber-50 p-3 rounded border border-amber-200 text-sm text-amber-900 font-bold mb-4">前4題由兒童回答(0-3分)，後3題由家長回答(0-5分)。</div> {childQuestions.map((q, idx) => ( <div key={idx} className="bg-white p-4 rounded-lg border-2 border-slate-200"> <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"> <span className="text-base font-bold text-black flex-1">{q}</span> <select className="border-2 border-slate-300 rounded px-3 py-2 text-base bg-white font-bold text-black w-full sm:w-auto" value={scores[idx]||0} onChange={e => updateScore(idx, Number(e.target.value))}> {[0,1,2,3,4,5].slice(0, idx < 4 ? 4 : 6).map(v => <option key={v} value={v}>{v}分</option>)} </select> </div> </div> ))} </div> )} <ResultCard title="ACT" result={result} copyContent={copyText} /> </div> ) };

export const Curb65Calculator: React.FC = () => { const [c, setC] = useState(false); const [u, setU] = useState(false); const [r, setR] = useState(false); const [b, setB] = useState(false); const [age, setAge] = useState(false); const [result, setResult] = useState<CalculatorResult | null>(null); useEffect(() => setResult(calculateCURB65(c,u?20:10,r?30:20,b,age)), [c,u,r,b,age]); const factors = [c&&'Confusion', u&&'Urea', r&&'RR', b&&'BP', age&&'Age65'].filter(Boolean).join(', '); const copyText = formatEMR('CURB-65', factors || 'None', result); return ( <div className="max-w-md space-y-2"> <Checkbox label="Confusion (意識混亂)" checked={c} onChange={setC} /> <Checkbox label="Urea (BUN > 19 mg/dL)" checked={u} onChange={setU} /> <Checkbox label="Respiratory Rate (≥ 30/min)" checked={r} onChange={setR} /> <Checkbox label="Blood Pressure (SBP<90 or DBP≤60)" checked={b} onChange={setB} /> <Checkbox label="Age ≥ 65 歲" checked={age} onChange={setAge} /> <ResultCard title="CURB-65" result={result} copyContent={copyText} /> </div> ) }

const MMRCCalculator: React.FC = () => { const [grade, setGrade] = useState(0); const result = calculateMMRC(grade); const copyText = formatEMR('mMRC', `Grade ${grade}`, result); return ( <div className="max-w-md animate-in fade-in"> <InputGroup label="活動性氣喘程度 (mMRC)"> <div className="space-y-3"> {[0,1,2,3,4].map(g => ( <button key={g} onClick={() => setGrade(g)} className={`w-full text-left p-4 rounded-lg border-2 text-base transition-all ${grade === g ? 'border-teal-600 bg-teal-50 text-teal-900 ring-2 ring-teal-600' : 'border-slate-300 bg-white text-slate-900 hover:bg-slate-50'}`}> <span className="font-black mr-2 text-black">Grade {g}:</span> <span className="font-bold">{calculateMMRC(g).interpretation}</span> </button> ))} </div> </InputGroup> <ResultCard title="mMRC" result={result} copyContent={copyText} /> </div> ) }

const CATCalculator: React.FC = () => { const [scores, setScores] = useState<number[]>(new Array(8).fill(0)); const result = calculateCAT(scores); const questions = [ { left: "我從不咳嗽", right: "我一直咳嗽" }, { left: "我肺裡完全沒有痰", right: "我肺裡充滿了痰" }, { left: "我沒有胸悶的感覺", right: "我有很嚴重的胸悶" }, { left: "我爬坡/上一層樓時不喘", right: "我爬坡/上一層樓時很喘" }, { left: "我在家裡的活動不受影響", right: "我在家裡的活動深受影響" }, { left: "儘管有肺病我仍有信心外出", right: "因為肺病我完全沒信心外出" }, { left: "我睡得很好", right: "因為肺病我睡不好" }, { left: "我精神很好", right: "我一點精神都沒有" } ]; const copyText = formatEMR('CAT Score', `Scores: [${scores.join(', ')}]`, result); const handleScoreChange = (idx: number, val: number) => { const newScores = [...scores]; newScores[idx] = val; setScores(newScores); }; return ( <div className="max-w-2xl animate-in fade-in"> <div className="bg-amber-50 p-4 mb-6 rounded-lg border border-amber-200 text-amber-900 text-sm font-bold"> <Info className="inline mr-2 mb-1" size={16}/> 請為每個項目評分 (0-5分)，0代表左邊狀況，5代表右邊狀況。 </div> <div className="space-y-6"> {questions.map((q, idx) => ( <div key={idx} className="bg-white p-4 rounded-lg border-2 border-slate-200 shadow-sm"> <div className="flex justify-between text-xs sm:text-sm font-bold text-slate-500 mb-2"> <span>{q.left} (0)</span> <span>{q.right} (5)</span> </div> <p className="font-bold text-black text-base mb-3 text-center bg-slate-100 py-1 rounded">{q.left} vs {q.right}</p> <div className="flex justify-between gap-1"> {[0,1,2,3,4,5].map(val => ( <button key={val} onClick={() => handleScoreChange(idx, val)} className={`flex-1 py-3 rounded font-bold text-lg border-2 transition-all ${scores[idx] === val ? 'bg-teal-700 text-white border-teal-700 shadow-md transform scale-105' : 'bg-white text-slate-400 border-slate-200 hover:border-slate-400 hover:text-slate-600'} `} > {val} </button> ))} </div> </div> ))} </div> <ResultCard title="CAT Score" result={result} copyContent={copyText} /> </div> ); }

export const COPDAssessmentCalculator: React.FC = () => { const [mode, setMode] = useState<'mmrc' | 'cat'>('mmrc'); return ( <div> <div className="max-w-md mb-6"> <Toggle options={[ {value: 'mmrc', label: '1. mMRC (呼吸困難)'}, {value: 'cat', label: '2. CAT (生活評估)'} ]} value={mode} onChange={setMode} /> </div> {mode === 'mmrc' ? <MMRCCalculator /> : <CATCalculator />} </div> ); }

export const ABGCalculator: React.FC = () => { const [ph, setPh] = useState<number|''>(''); const [pco2, setPco2] = useState<number|''>(''); const [hco3, setHco3] = useState<number|''>(''); const [result, setResult] = useState<CalculatorResult|null>(null); useEffect(() => { if(ph && pco2 && hco3) setResult(calculateABG(Number(ph), Number(pco2), Number(hco3))); else setResult(null); }, [ph, pco2, hco3]); const copyText = formatEMR('ABG', `pH ${ph}, pCO2 ${pco2}, HCO3 ${hco3}`, result); return (<div className="max-w-md space-y-4"><InputGroup label="pH"><NumberInput value={ph} onChange={setPh} step="0.01" /></InputGroup><div className="grid grid-cols-2 gap-4"><InputGroup label="pCO2 (mmHg)"><NumberInput value={pco2} onChange={setPco2} /></InputGroup><InputGroup label="HCO3 (mEq/L)"><NumberInput value={hco3} onChange={setHco3} /></InputGroup></div><ResultCard title="ABG Analysis" result={result} copyContent={copyText} /></div>); };
